version: '3'
services:
  pelorus-pastdue:
    build:
      context: .
      dockerfile: Dockerfile
    image: sccity/pelorus-pastdue:latest
    container_name: pelorus-pastdue
    environment:
      - TZ=America/Denver
    ports:
      - "8080:5000"
    volumes:
      - "$PWD/.env:/app/.env:ro"
    restart: unless-stopped
    user: "1435:1435" 
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M